---
- hosts: network
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy Quagga daemons
      copy: src=config/{{ansible_hostname}}/daemons dest=/etc/quagga/
    - name: copy Quagga conf
      copy: src=config/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
    - name: reload networking
      command: ifreload -a
    - name: reload quagga
      service: name=quagga state=restarted

- hosts: servers
#  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-ifupdown2
  tasks:
    - name: copy interfaces
      copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/      
    - name: restarts networking with their new configuration
      command: ifreload -a
